export const CITIES = [
  "Tashkent",
  "Samarkand",
  "Bukhara",
  "Namangan",
  "Andijan",
  "Fergana",
  "Nukus",
  "Termez",
  "Qarshi",
  "Jizzakh",
  "Other",
] as const;

/** Team wizard / team profiles — matches product spec */
export const TEAM_WORK_OPTIONS = [
  "Full-time project",
  "Part-time project",
  "Remote",
  "On-site",
] as const;

export const TEAM_AVAILABILITY = [
  "Available now",
  "Available in 1 month",
  "Open to offers",
] as const;

export const JOB_CATEGORIES = [
  "Education & Teaching",
  "Technology & IT",
  "Business & Finance",
  "Healthcare",
  "Creative & Design",
  "Engineering",
  "Legal & Government",
  "Service & Hospitality",
  "Other",
] as const;

export const INDUSTRIES = [
  "Technology",
  "Education",
  "Healthcare",
  "Finance",
  "Retail",
  "Manufacturing",
  "Government",
  "Media",
  "Hospitality",
  "Other",
] as const;

export const SUBCATEGORIES: Record<string, string[]> = {
  "Education & Teaching": [
    "IELTS Teacher",
    "TOEFL Teacher",
    "Math Teacher",
    "Physics Teacher",
    "Chemistry Teacher",
    "Biology Teacher",
    "Primary School Teacher",
    "Language Coach",
    "University Tutor",
    "Online Tutor",
    "Preschool Teacher",
    "University Lecturer",
    "Private Tutor",
    "Music Teacher",
    "Sports Coach",
  ],
  "Technology & IT": [
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "Mobile Developer iOS",
    "Mobile Developer Android",
    "React Native Developer",
    "UI/UX Designer",
    "Data Analyst",
    "Data Scientist",
    "DevOps Engineer",
    "System Administrator",
    "Cybersecurity Specialist",
    "QA Engineer",
    "IT Project Manager",
  ],
  "Business & Finance": [
    "Accountant",
    "Financial Analyst",
    "Auditor",
    "Tax Specialist",
    "Business Analyst",
    "Project Manager",
    "Product Manager",
    "Sales Manager",
    "HR Manager",
    "Marketing Specialist",
    "Digital Marketer",
    "SMM Specialist",
    "Recruiter",
    "Procurement Specialist",
    "Logistics Manager",
  ],
  "Healthcare": [
    "General Practitioner",
    "Surgeon",
    "Dentist",
    "Pediatrician",
    "Nurse",
    "Pharmacist",
    "Lab Technician",
    "Physiotherapist",
    "Psychologist",
    "Nutritionist",
    "Medical Administrator",
  ],
  "Creative & Design": [
    "Graphic Designer",
    "Brand Designer",
    "UI/UX Designer",
    "Illustrator",
    "Animator",
    "Motion Designer",
    "Video Editor",
    "Videographer",
    "Photographer",
    "Copywriter",
    "Content Writer",
    "Journalist",
    "Translator",
    "Interpreter",
    "Music Producer",
  ],
  "Engineering": [
    "Civil Engineer",
    "Structural Engineer",
    "Mechanical Engineer",
    "Electrical Engineer",
    "Architect",
    "Interior Designer",
    "Construction Manager",
    "Site Engineer",
    "AutoCAD Specialist",
    "BIM Specialist",
  ],
  "Legal & Government": [
    "Lawyer",
    "Corporate Lawyer",
    "Criminal Lawyer",
    "Legal Consultant",
    "Notary",
    "Compliance Officer",
    "Contract Manager",
    "Legal Translator",
    "Government Official",
  ],
  "Service & Hospitality": [
    "Hotel Manager",
    "Front Desk Staff",
    "Tour Guide",
    "Travel Agent",
    "Chef",
    "Sous Chef",
    "Waiter",
    "Bartender",
    "Barista",
    "Restaurant Manager",
    "Event Planner",
    "Driver",
    "Security Guard",
    "Customer Service Rep",
    "Call Center Agent",
  ],
  "Other": ["Any profession not covered by above categories"],
};
